export enum EDocuSignStatus {
    AWAITING_SIGNATURE = "awaiting_signature",
    SELLER_SIGNED = "seller_signed",
    SELLER_UPDATE_REQUESTED = "update_requested",
    SELLER_DECLINED = "seller_declined",
    SELLER_VOIDED = "seller_voided",
    BUYER_SIGNED = "buyer_signed",
    AGREEMENT_BUYER_SIGNED = "agreement_buyer_signed",
    AGREEMENT_EXPIRE = "agreement_expired",
    BUYER_DECLINED = "buyer_declined",
    BUYER_VOIDED = "buyer_voided",
    BUYER_UPDATE_REQUESTED = SELLER_UPDATE_REQUESTED,
    ALL_SIGNED = "signed",
    REJECTED = "rejected",
    EXPIRED = "expired",
    PENDING = "pending",
    BUYER_SEND = "sent",
}
