/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
    | "Pacific/Midway"
    | "Pacific/Niue"
    | "Pacific/Honolulu"
    | "Pacific/Rarotonga"
    | "America/Anchorage"
    | "Pacific/Gambier"
    | "America/Los_Angeles"
    | "America/Tijuana"
    | "America/Denver"
    | "America/Phoenix"
    | "America/Chicago"
    | "America/Guatemala"
    | "America/New_York"
    | "America/Bogota"
    | "America/Caracas"
    | "America/Santiago"
    | "America/Buenos_Aires"
    | "America/Sao_Paulo"
    | "Atlantic/South_Georgia"
    | "Atlantic/Azores"
    | "Atlantic/Cape_Verde"
    | "Europe/London"
    | "Europe/Berlin"
    | "Africa/Lagos"
    | "Europe/Athens"
    | "Africa/Cairo"
    | "Europe/Moscow"
    | "Asia/Riyadh"
    | "Asia/Dubai"
    | "Asia/Baku"
    | "Asia/Karachi"
    | "Asia/Tashkent"
    | "Asia/Calcutta"
    | "Asia/Dhaka"
    | "Asia/Almaty"
    | "Asia/Jakarta"
    | "Asia/Bangkok"
    | "Asia/Shanghai"
    | "Asia/Singapore"
    | "Asia/Tokyo"
    | "Asia/Seoul"
    | "Australia/Brisbane"
    | "Australia/Sydney"
    | "Pacific/Guam"
    | "Pacific/Noumea"
    | "Pacific/Auckland"
    | "Pacific/Fiji";

export interface Config {
    auth: {
        "cms-users": CmsUserAuthOperations;
    };
    blocks: {};
    collections: {
        "resource-topics": ResourceTopic;
        "resource-guides": ResourceGuide;
        "resource-faq-groups": ResourceFaqGroup;
        "resource-faqs": ResourceFaq;
        media: Media;
        "cms-users": CmsUser;
        "payload-kv": PayloadKv;
        "payload-jobs": PayloadJob;
        "payload-locked-documents": PayloadLockedDocument;
        "payload-preferences": PayloadPreference;
        "payload-migrations": PayloadMigration;
    };
    collectionsJoins: {};
    collectionsSelect: {
        "resource-topics":
            | ResourceTopicsSelect<false>
            | ResourceTopicsSelect<true>;
        "resource-guides":
            | ResourceGuidesSelect<false>
            | ResourceGuidesSelect<true>;
        "resource-faq-groups":
            | ResourceFaqGroupsSelect<false>
            | ResourceFaqGroupsSelect<true>;
        "resource-faqs": ResourceFaqsSelect<false> | ResourceFaqsSelect<true>;
        media: MediaSelect<false> | MediaSelect<true>;
        "cms-users": CmsUsersSelect<false> | CmsUsersSelect<true>;
        "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
        "payload-jobs": PayloadJobsSelect<false> | PayloadJobsSelect<true>;
        "payload-locked-documents":
            | PayloadLockedDocumentsSelect<false>
            | PayloadLockedDocumentsSelect<true>;
        "payload-preferences":
            | PayloadPreferencesSelect<false>
            | PayloadPreferencesSelect<true>;
        "payload-migrations":
            | PayloadMigrationsSelect<false>
            | PayloadMigrationsSelect<true>;
    };
    db: {
        defaultIDType: number;
    };
    fallbackLocale: null;
    globals: {
        "resource-settings": ResourceSetting;
    };
    globalsSelect: {
        "resource-settings":
            | ResourceSettingsSelect<false>
            | ResourceSettingsSelect<true>;
    };
    locale: null;
    widgets: {
        collections: CollectionsWidget;
    };
    user: CmsUser;
    jobs: {
        tasks: {
            schedulePublish: TaskSchedulePublish;
            inline: {
                input: unknown;
                output: unknown;
            };
        };
        workflows: unknown;
    };
}
export interface CmsUserAuthOperations {
    forgotPassword: {
        email: string;
        password: string;
    };
    login: {
        email: string;
        password: string;
    };
    registerFirstUser: {
        email: string;
        password: string;
    };
    unlock: {
        email: string;
        password: string;
    };
}
/**
 * Create and organise the topics customers use to browse the Resources library.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-topics".
 */
export interface ResourceTopic {
    id: number;
    title: string;
    /**
     * When enabled, the slug will auto-generate from the title field on save and autosave.
     */
    generateSlug?: boolean | null;
    slug: string;
    previousSlugs?:
        | {
              slug: string;
              id?: string | null;
          }[]
        | null;
    /**
     * A concise introduction displayed on the Resources landing page.
     */
    description: string;
    /**
     * Select the icon that best represents this topic on the Resources landing page.
     */
    icon: "buying" | "selling" | "marketplace" | "whisky-casks";
    /**
     * Controls the topic order. Lower numbers appear first.
     */
    sortOrder: number;
    updatedAt: string;
    createdAt: string;
    _status?: ("draft" | "published") | null;
}
/**
 * Create, organise and publish educational content for the Resources library.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-guides".
 */
export interface ResourceGuide {
    id: number;
    title: string;
    /**
     * When enabled, the slug will auto-generate from the title field on save and autosave.
     */
    generateSlug?: boolean | null;
    slug: string;
    previousSlugs?:
        | {
              slug: string;
              id?: string | null;
          }[]
        | null;
    /**
     * A short summary displayed on guide cards and in search results.
     */
    excerpt: string;
    /**
     * Determines the guide's main category and public URL.
     */
    primaryTopic: number | ResourceTopic;
    /**
     * Optional additional topics that help customers discover this guide.
     */
    relatedTopics?: (number | ResourceTopic)[] | null;
    /**
     * Structure the article with clear headings, concise paragraphs, lists and relevant links.
     */
    content: {
        root: {
            type: string;
            children: {
                type: any;
                version: number;
                [k: string]: unknown;
            }[];
            direction: ("ltr" | "rtl") | null;
            format:
                | "left"
                | "start"
                | "center"
                | "right"
                | "end"
                | "justify"
                | "";
            indent: number;
            version: number;
        };
        [k: string]: unknown;
    };
    /**
     * Leave blank to calculate reading time automatically from the guide content.
     */
    readTimeMinutes?: number | null;
    /**
     * Displayed on guide cards. Use a clear landscape image with meaningful alternative text.
     */
    coverImage?: (number | null) | Media;
    /**
     * Controls the guide order within its topic. Lower numbers appear first.
     */
    sortOrder: number;
    updatedAt: string;
    createdAt: string;
    _status?: ("draft" | "published") | null;
}
/**
 * Upload and manage images used across Resources content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
    id: number;
    /**
     * Describe the image's purpose for customers who use screen readers.
     */
    alt: string;
    prefix?: string | null;
    updatedAt: string;
    createdAt: string;
    url?: string | null;
    thumbnailURL?: string | null;
    filename?: string | null;
    mimeType?: string | null;
    filesize?: number | null;
    width?: number | null;
    height?: number | null;
    focalX?: number | null;
    focalY?: number | null;
    sizes?: {
        card?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        thumbnail?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
    };
}
/**
 * Create and arrange the groups displayed on the Resources FAQ page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-faq-groups".
 */
export interface ResourceFaqGroup {
    id: number;
    title: string;
    /**
     * When enabled, the slug will auto-generate from the title field on save and autosave.
     */
    generateSlug?: boolean | null;
    slug: string;
    /**
     * Controls the group order on the FAQ page. Lower numbers appear first.
     */
    sortOrder: number;
    updatedAt: string;
    createdAt: string;
    _status?: ("draft" | "published") | null;
}
/**
 * Create and organise clear answers to common customer questions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-faqs".
 */
export interface ResourceFaq {
    id: number;
    question: string;
    /**
     * Provide a direct, accurate answer. Use formatting only when it improves readability.
     */
    answer: {
        root: {
            type: string;
            children: {
                type: any;
                version: number;
                [k: string]: unknown;
            }[];
            direction: ("ltr" | "rtl") | null;
            format:
                | "left"
                | "start"
                | "center"
                | "right"
                | "end"
                | "justify"
                | "";
            indent: number;
            version: number;
        };
        [k: string]: unknown;
    };
    /**
     * Select the group where this question appears on the FAQ page.
     */
    group: number | ResourceFaqGroup;
    topics?: (number | ResourceTopic)[] | null;
    /**
     * Used as a fallback when no Popular FAQs are selected in Resource Listing.
     */
    isPopular?: boolean | null;
    /**
     * Controls the FAQ order. Lower numbers appear first.
     */
    sortOrder: number;
    updatedAt: string;
    createdAt: string;
    _status?: ("draft" | "published") | null;
}
/**
 * Manage access for editors and administrators of the content management system.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users".
 */
export interface CmsUser {
    id: number;
    /**
     * Editors manage content. Administrators can also manage CMS users.
     */
    role: "editor" | "administrator";
    updatedAt: string;
    createdAt: string;
    email: string;
    resetPasswordToken?: string | null;
    resetPasswordExpiration?: string | null;
    salt?: string | null;
    hash?: string | null;
    loginAttempts?: number | null;
    lockUntil?: string | null;
    sessions?:
        | {
              id: string;
              createdAt?: string | null;
              expiresAt: string;
          }[]
        | null;
    password?: string | null;
    collection: "cms-users";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
    id: number;
    key: string;
    data:
        | {
              [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
    id: number;
    /**
     * Input data provided to the job
     */
    input?:
        | {
              [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    taskStatus?:
        | {
              [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    completedAt?: string | null;
    totalTried?: number | null;
    /**
     * If hasError is true this job will not be retried
     */
    hasError?: boolean | null;
    /**
     * If hasError is true, this is the error that caused it
     */
    error?:
        | {
              [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    /**
     * Task execution log
     */
    log?:
        | {
              executedAt: string;
              completedAt: string;
              taskSlug: "inline" | "schedulePublish";
              taskID: string;
              input?:
                  | {
                        [k: string]: unknown;
                    }
                  | unknown[]
                  | string
                  | number
                  | boolean
                  | null;
              output?:
                  | {
                        [k: string]: unknown;
                    }
                  | unknown[]
                  | string
                  | number
                  | boolean
                  | null;
              state: "failed" | "succeeded";
              error?:
                  | {
                        [k: string]: unknown;
                    }
                  | unknown[]
                  | string
                  | number
                  | boolean
                  | null;
              id?: string | null;
          }[]
        | null;
    taskSlug?: ("inline" | "schedulePublish") | null;
    queue?: string | null;
    waitUntil?: string | null;
    processing?: boolean | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
    id: number;
    document?:
        | ({
              relationTo: "resource-topics";
              value: number | ResourceTopic;
          } | null)
        | ({
              relationTo: "resource-guides";
              value: number | ResourceGuide;
          } | null)
        | ({
              relationTo: "resource-faq-groups";
              value: number | ResourceFaqGroup;
          } | null)
        | ({
              relationTo: "resource-faqs";
              value: number | ResourceFaq;
          } | null)
        | ({
              relationTo: "media";
              value: number | Media;
          } | null)
        | ({
              relationTo: "cms-users";
              value: number | CmsUser;
          } | null);
    globalSlug?: string | null;
    user: {
        relationTo: "cms-users";
        value: number | CmsUser;
    };
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
    id: number;
    user: {
        relationTo: "cms-users";
        value: number | CmsUser;
    };
    key?: string | null;
    value?:
        | {
              [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
    id: number;
    name?: string | null;
    batch?: number | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-topics_select".
 */
export interface ResourceTopicsSelect<T extends boolean = true> {
    title?: T;
    generateSlug?: T;
    slug?: T;
    previousSlugs?:
        | T
        | {
              slug?: T;
              id?: T;
          };
    description?: T;
    icon?: T;
    sortOrder?: T;
    updatedAt?: T;
    createdAt?: T;
    _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-guides_select".
 */
export interface ResourceGuidesSelect<T extends boolean = true> {
    title?: T;
    generateSlug?: T;
    slug?: T;
    previousSlugs?:
        | T
        | {
              slug?: T;
              id?: T;
          };
    excerpt?: T;
    primaryTopic?: T;
    relatedTopics?: T;
    content?: T;
    readTimeMinutes?: T;
    coverImage?: T;
    sortOrder?: T;
    updatedAt?: T;
    createdAt?: T;
    _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-faq-groups_select".
 */
export interface ResourceFaqGroupsSelect<T extends boolean = true> {
    title?: T;
    generateSlug?: T;
    slug?: T;
    sortOrder?: T;
    updatedAt?: T;
    createdAt?: T;
    _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-faqs_select".
 */
export interface ResourceFaqsSelect<T extends boolean = true> {
    question?: T;
    answer?: T;
    group?: T;
    topics?: T;
    isPopular?: T;
    sortOrder?: T;
    updatedAt?: T;
    createdAt?: T;
    _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
    alt?: T;
    prefix?: T;
    updatedAt?: T;
    createdAt?: T;
    url?: T;
    thumbnailURL?: T;
    filename?: T;
    mimeType?: T;
    filesize?: T;
    width?: T;
    height?: T;
    focalX?: T;
    focalY?: T;
    sizes?:
        | T
        | {
              card?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              thumbnail?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
          };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users_select".
 */
export interface CmsUsersSelect<T extends boolean = true> {
    role?: T;
    updatedAt?: T;
    createdAt?: T;
    email?: T;
    resetPasswordToken?: T;
    resetPasswordExpiration?: T;
    salt?: T;
    hash?: T;
    loginAttempts?: T;
    lockUntil?: T;
    sessions?:
        | T
        | {
              id?: T;
              createdAt?: T;
              expiresAt?: T;
          };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
    key?: T;
    data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
    input?: T;
    taskStatus?: T;
    completedAt?: T;
    totalTried?: T;
    hasError?: T;
    error?: T;
    log?:
        | T
        | {
              executedAt?: T;
              completedAt?: T;
              taskSlug?: T;
              taskID?: T;
              input?: T;
              output?: T;
              state?: T;
              error?: T;
              id?: T;
          };
    taskSlug?: T;
    queue?: T;
    waitUntil?: T;
    processing?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
    document?: T;
    globalSlug?: T;
    user?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
    user?: T;
    key?: T;
    value?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
    name?: T;
    batch?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * Curate the featured content and popular questions shown on the Resources landing page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-settings".
 */
export interface ResourceSetting {
    id: number;
    /**
     * Select and arrange up to four published guides or FAQs for the featured section.
     */
    featuredResources: (
        | {
              relationTo: "resource-guides";
              value: number | ResourceGuide;
          }
        | {
              relationTo: "resource-faqs";
              value: number | ResourceFaq;
          }
    )[];
    /**
     * Legacy featured guide selections retained during the featured resources migration.
     */
    featuredGuides?: (number | ResourceGuide)[] | null;
    /**
     * Select and arrange the questions displayed in the Popular FAQs section.
     */
    popularFaqs?: (number | ResourceFaq)[] | null;
    _status?: ("draft" | "published") | null;
    updatedAt?: string | null;
    createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-settings_select".
 */
export interface ResourceSettingsSelect<T extends boolean = true> {
    featuredResources?: T;
    featuredGuides?: T;
    popularFaqs?: T;
    _status?: T;
    updatedAt?: T;
    createdAt?: T;
    globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
    data?: {
        [k: string]: unknown;
    };
    width: "full";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
    input: {
        type?: ("publish" | "unpublish") | null;
        locale?: string | null;
        doc?:
            | ({
                  relationTo: "resource-topics";
                  value: number | ResourceTopic;
              } | null)
            | ({
                  relationTo: "resource-guides";
                  value: number | ResourceGuide;
              } | null)
            | ({
                  relationTo: "resource-faq-groups";
                  value: number | ResourceFaqGroup;
              } | null)
            | ({
                  relationTo: "resource-faqs";
                  value: number | ResourceFaq;
              } | null);
        global?: "resource-settings" | null;
        user?: (number | null) | CmsUser;
    };
    output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
    [k: string]: unknown;
}

declare module "payload" {
    export interface GeneratedTypes extends Config {}
}
